// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFgr8RsX9uYc02aDU8n7G_I_QAzu5dHoc',
    appId: '1:157331009198:web:f4f2f0205b6bf64269473f',
    messagingSenderId: '157331009198',
    projectId: 'marvelapp-d8a53',
    authDomain: 'marvelapp-d8a53.firebaseapp.com',
    storageBucket: 'marvelapp-d8a53.firebasestorage.app',
    measurementId: 'G-N55367C8KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaxlMJp4cYLiaM8i_u_yXRStbTqdmT4OM',
    appId: '1:157331009198:android:313290eaa1bdc15b69473f',
    messagingSenderId: '157331009198',
    projectId: 'marvelapp-d8a53',
    storageBucket: 'marvelapp-d8a53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHPY0ES3ROVwG_s3981pdZbDCzhE6b0XQ',
    appId: '1:157331009198:ios:71365caffd08cd6469473f',
    messagingSenderId: '157331009198',
    projectId: 'marvelapp-d8a53',
    storageBucket: 'marvelapp-d8a53.firebasestorage.app',
    iosBundleId: 'com.example.marvelAnimationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHPY0ES3ROVwG_s3981pdZbDCzhE6b0XQ',
    appId: '1:157331009198:ios:71365caffd08cd6469473f',
    messagingSenderId: '157331009198',
    projectId: 'marvelapp-d8a53',
    storageBucket: 'marvelapp-d8a53.firebasestorage.app',
    iosBundleId: 'com.example.marvelAnimationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFgr8RsX9uYc02aDU8n7G_I_QAzu5dHoc',
    appId: '1:157331009198:web:16b57309a505e81969473f',
    messagingSenderId: '157331009198',
    projectId: 'marvelapp-d8a53',
    authDomain: 'marvelapp-d8a53.firebaseapp.com',
    storageBucket: 'marvelapp-d8a53.firebasestorage.app',
    measurementId: 'G-LKVZVDD9EL',
  );
}
